global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  receiver: 'email'
  
receivers:
- name: 'email'
  email_configs:
  - to: 'rasckey817@gmail.com'
    from: 'mailtrap@demomailtrap.com'
    smarthost: 'live.smtp.mailtrap.io:587'
    auth_username: 'api'
    auth_password: '985a9ca82363e65307e43e3ef570554f'
    auth_identity: ''
    require_tls: true